#!/usr/bin/env bash
# Author: JunyoungJung
# Date: 2026-03-17

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../../.." && pwd)
COMMANDS_DIR="$REPO_ROOT/.codex/commands"
DEFAULT_DEST_DIR="$HOME/.codex/prompts"
DEST_DIR="${CODEX_PROMPT_DEST:-$DEFAULT_DEST_DIR}"
PREFIX="${CODEX_PROMPT_PREFIX:-}"
CLEAN_STALE=false
DRY_RUN=false

usage() {
  cat <<'EOF'
Usage:
  sync-codex-prompts.sh [DEST_DIR]
  sync-codex-prompts.sh [--dest DIR] [--prefix PREFIX] [--clean] [--dry-run]

Options:
  --dest DIR     Prompt output directory. Default: ~/.codex/prompts
  --prefix TEXT  Prefix added to generated prompt names.
  --clean        Remove stale prompt files previously generated by this script.
  --dry-run      Print planned changes without writing files.
  --help         Show this help message.

Environment:
  CODEX_PROMPT_DEST    Default destination directory override
  CODEX_PROMPT_PREFIX  Default prompt prefix override
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dest)
      [ $# -ge 2 ] || {
        echo "[sync-codex-prompts] --dest requires a path" >&2
        exit 1
      }
      DEST_DIR="$2"
      shift 2
      ;;
    --prefix)
      [ $# -ge 2 ] || {
        echo "[sync-codex-prompts] --prefix requires a value" >&2
        exit 1
      }
      PREFIX="$2"
      shift 2
      ;;
    --clean)
      CLEAN_STALE=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --*)
      echo "[sync-codex-prompts] unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
    *)
      DEST_DIR="$1"
      shift
      ;;
  esac
done

yaml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

extract_description() {
  awk '
    /^# / { next }
    /^## / { exit }
    NF {
      line = $0
      gsub(/^[-*][[:space:]]+/, "", line)
      print line
      exit
    }
  ' "$1"
}

extract_argument_hint() {
  awk '
    /^## 입력/ { in_input = 1; next }
    /^## / && in_input { exit }
    in_input && match($0, /`[^`]+`/) {
      token = substr($0, RSTART + 1, RLENGTH - 2)
      if ($0 ~ /필수/) {
        printf "%s<%s>", sep, token
      } else {
        printf "%s[%s]", sep, token
      }
      sep = " "
    }
    END {
      if (sep != "") {
        print ""
      }
    }
  ' "$1"
}

write_prompt_file() {
  local command_file="$1"
  local prompt_file="$2"
  local prompt_name="$3"
  local description="$4"
  local argument_hint="$5"

  {
    printf -- '---\n'
    printf 'description: "%s"\n' "$(yaml_escape "$description")"
    if [ -n "$argument_hint" ]; then
      printf 'argument-hint: "%s"\n' "$(yaml_escape "$argument_hint")"
    fi
    printf -- '---\n\n'
    printf '이 프롬프트는 `%s` 문서를 Codex custom prompt로 노출합니다.\n' "$prompt_name"
    printf '사용자가 `/prompts:%s` 뒤에 추가로 입력한 텍스트가 있으면 그 값을 실행 인자로 해석하세요.\n' "$prompt_name"
    printf '가능하면 먼저 문서에 있는 실행 스크립트를 사용하고, 권한이나 환경 제약이 있으면 수동 절차를 따르세요.\n\n'
    printf '원본 문서: `%s`\n\n' "${command_file#$REPO_ROOT/}"
    cat "$command_file"
    printf '\n'
  } > "$prompt_file"
}

if [ "$DRY_RUN" = false ]; then
  mkdir -p "$DEST_DIR"
fi

generated=0
removed=0
managed_prompts=()

for command_file in "$COMMANDS_DIR"/*.md; do
  [ -f "$command_file" ] || continue

  base_name=$(basename "$command_file" .md)
  case "$base_name" in
    *-manual)
      continue
      ;;
  esac

  prompt_name="${PREFIX}${base_name}"
  prompt_file="$DEST_DIR/$prompt_name.md"
  description=$(extract_description "$command_file")
  argument_hint=$(extract_argument_hint "$command_file")
  managed_prompts+=("$prompt_name.md")

  if [ -z "$description" ]; then
    description="$base_name command"
  fi

  if [ "$DRY_RUN" = true ]; then
    printf '[sync-codex-prompts] would generate: %s\n' "$prompt_file"
  else
    write_prompt_file "$command_file" "$prompt_file" "$prompt_name" "$description" "$argument_hint"
    printf '[sync-codex-prompts] generated: %s\n' "$prompt_file"
  fi

  generated=$((generated + 1))
done

if [ "$CLEAN_STALE" = true ] && [ -d "$DEST_DIR" ]; then
  for existing_file in "$DEST_DIR"/*.md; do
    [ -f "$existing_file" ] || continue

    existing_base=$(basename "$existing_file")
    keep_file=false
    for managed_name in "${managed_prompts[@]}"; do
      if [ "$existing_base" = "$managed_name" ]; then
        keep_file=true
        break
      fi
    done

    if [ "$keep_file" = false ]; then
      if [ "$DRY_RUN" = true ]; then
        printf '[sync-codex-prompts] would remove stale: %s\n' "$existing_file"
      else
        rm -f "$existing_file"
        printf '[sync-codex-prompts] removed stale: %s\n' "$existing_file"
      fi
      removed=$((removed + 1))
    fi
  done
fi

printf '[sync-codex-prompts] completed: generated=%s removed=%s dest=%s\n' "$generated" "$removed" "$DEST_DIR"
printf '[sync-codex-prompts] prompts are available as /prompts:<name> after Codex reload if needed.\n'
